name: AsperienRanks
version: '1.0'
main: asperienranks.asperienranks.AsperienRanks
api-version: 1.17
load: STARTUP
depend: [ Vault, Essentials ]
authors: [ Lagggpixel ]
description: AsperienRanks
commands:
  rank:
    description: Opens a gui allowing you to rankup.
    usage: /rank
    permission: asperienranks.default
    permission-message: You don't have premission to do this, please relog or contact a server admin
  rankup:
    description: Ranks up
    usage: /rankup
    permission: asperienranks.default
    permission-message: You don't have premission to do this, please relog or contact a server admin
  forcerankup:
    description: Forces the rankup of a player(does not use their money)
    usage: /forcerankup [player]
    permission: asperienranks.forcerankup
    permission-message: You can't do this!
    alisas: [frankup]
  info:
    description: Checks the player's information
    usage: /info [player]
    permission: asperienranks.info
    permission-message: You can't do this!
    aliases: [i]
permissions:
  asperienranks.*:
    description: All other permmisions
    children:
      - asperienranks.master
      - asperienranks.forcerankup
    default: false
  asperienranks.forcerankup:
    description: Allows your player to force a rankup
    default: op
  asperienranks.info:
    description: Allows the player to see others' info
    default: op
  asperienranks.master:
    description: Grants you all of the other ranks.
    children:
      - asperienranks.emperor
      - asperienranks.shogun
      - asperienranks.daimyo
      - asperienranks.samurai
      - asperienranks.ronin
      - asperienranks.liege
      - asperienranks.elite
      - asperienranks.soldier
      - asperienranks.merchant
      - asperienranks.member
      - asperienranks.default
    default: false
  asperienranks.emperor:
    children: [asperienranks.shogun]
    default: false
  asperienranks.shogun:
    children: [asperienranks.daimyo]
    default: false
  asperienranks.daimyo:
    children: [asperienranks.samurai]
    default: false
  asperienranks.samurai:
    children: [asperienranks.ronin]
    default: false
  asperienranks.ronin:
    children: [asperienranks.liege]
    default: false
  asperienranks.liege:
    children: [asperienranks.elite]
    default: false
  asperienranks.elite:
    children: [asperienranks.soldier]
    default: false
  asperienranks.soldier:
    children: [asperienranks.merchant]
    default: false
  asperienranks.merchant:
    children: [asperienranks.member]
    default: false
  asperienranks.member:
    children: [asperienranks.default]
    default: false
  asperienranks.default:
    default: true