name: AsperienRanks
version: '1.0'
main: asperienranks.asperienranks.AsperienRanks
api-version: 1.17
depend: [ Vault ]
authors: [ Lagggpixel ]
description: AsperienRanks
commands:
  rank:
    description: Opens a gui allowing you to rankup.
    usage: /rank
permissions:
  asperienranks.*:
    description: All other permmisions
    children:
      - asperienranks.master
  asperienranks.master:
    description: Grants you all of the other ranks.
    children:
      - asperienranks.emperor
      - asperienranks.shogun
      - asperienranks.daimyo
      - asperienranks.samurai
      - asperienranks.ronin
      - asperienranks.liege
      - asperienranks.elite
      - asperienranks.soldier
      - asperienranks.merchant
      - asperienranks.member
      - asperienranks.default
  asperienranks.emperor:
    children: [asperienranks.shogun]
    default: false
  asperienranks.shogun:
    children: [asperienranks.daimyo]
    default: false
  asperienranks.daimyo:
    children: [asperienranks.samurai]
    default: false
  asperienranks.samurai:
    children: [asperienranks.ronin]
    default: false
  asperienranks.ronin:
    children: [asperienranks.liege]
    default: false
  asperienranks.liege:
    children: [asperienranks.elite]
    default: false
  asperienranks.elite:
    children: [asperienranks.soldier]
    default: false
  asperienranks.soldier:
    children: [asperienranks.merchant]
    default: false
  asperienranks.merchant:
    children: [asperienranks.member]
    default: false
  asperienranks.member:
    children: [asperienranks.default]
    default: false
  asperienranks.default:
    default: true